### ISSUE TITLE
:))

### ISSUE THREAD

**Issue by Trung27012003** [lebathang/lebathang#3]
Ông ơi tôi hỏi cái, cái kia tôi bị phốt gì thế, không biết đăng nhập vào cái gì bị nó chiếm quyền gắn 1 đống star với project

**Comment by lebathang** [comment]
> Ông ơi tôi hỏi cái, cái kia tôi bị phốt gì thế, không biết đăng nhập vào cái gì bị nó chiếm quyền gắn 1 đống star với project

tôi ngồi đọc đống coment thì thấy bọn kia bảo ô share link project github mà gắn viruss r còn lấy github contributor của ngta gắn vào phần read me nx :))))

**Comment by Trung27012003** [comment]
ui  ông cho tôi xin link với, cái github contributor tôi xem trên ytb nó dùng web generate ra, còn cái project kia nãy nãy tôi vào mới thấy đứa nào đăng ấy không phải tôi :(((

**Comment by lebathang** [comment]
> ui ông cho tôi xin link với, cái github contributor tôi xem trên ytb nó dùng web generate ra, còn cái project kia nãy nãy tôi vào mới thấy đứa nào đăng ấy không phải tôi :(((

vào đây mà đọc này daika
[voz](https://voz.vn/t/tong-hop-cac-phan-mem-mien-phi-ma-nguon-mo-tren-pc.907641/post-32020132)

**Comment by Trung27012003** [comment]
tôi cảm ơn ông nhiều nha
